---
# Ignored, since newer distros don't need this package
# https://github.com/jnv/ansible-role-unattended-upgrades/issues/6
- name: ensure update-notifier-common is installed
  apt:
    name: update-notifier-common
    state: present 
    update_cache: yes
  become: true
  ignore_errors: true

